project:
  type: website

website:
  title: "IS415-Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/deadline2359/IS415-Project
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

